export { default as LoginPage } from './LoginPage.vue'
export { default as HomePage } from './HomePage.vue'
export { default as TeamPage } from './TeamPage.vue'
export * from './ConditionMonitoringPage'
export { default as HistoryMaintenancePage } from './HistoryMaintenancePage/HistoryMaintenancePage.vue'
export * from './WorkPlanPage'
export { default as CapexPage } from './CapexPage.vue'
export * from './MdoTdoPage'
export { default as SinkPage } from '@/views/SinkPage.vue'
export * from './HistoryMaintenancePage'
export { default as ParentView } from './ParentView.vue'
export { default as LangkahkerjaPage } from './LangkahKerjaPage.vue'